name: API Tests with RestAssured

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # Step 3: Cache Maven dependencies (optional but faster)
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build and run TestNG tests
      - name: Run TestNG tests
        run: mvn clean test

      # Step 5: Upload TestNG reports as artifacts
      - name: Upload TestNG HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Report
          path: target/surefire-reports/
