name: API Tests with RestAssured

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      # Step 3: Cache Maven dependencies
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Detect pom.xml location
      - name: Detect pom.xml location
        id: find-pom
        run: |
          if [ -f "pom.xml" ]; then
            echo "POM_DIR=." >> $GITHUB_ENV
          else
            POM_PATH=$(find . -name "pom.xml" | head -n 1)
            if [ -z "$POM_PATH" ]; then
              echo "No pom.xml found!"
              exit 1
            fi
            POM_DIR=$(dirname "$POM_PATH")
            echo "POM_DIR=$POM_DIR" >> $GITHUB_ENV
          fi
          echo "POM directory is $POM_DIR"

      # Step 5: Run Maven tests
      - name: Run Maven tests
        run: |
          cd $POM_DIR
          mvn clean test -X
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"

      # Step 6: Upload TestNG report
      - name: Upload TestNG report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Report
          path: ${{ env.POM_DIR }}/target/surefire-reports/
